import type { ParamSchema } from "./ParamStore";

export const analysisSchemas: ParamSchema[] = [
  {
    key: "dsp.windowSize",
    label: "Window size",
    kind: "discrete",
    options: [512, 1024, 2048, 4096],
    default: 2048,
    reconfig: true,
  },
  {
    key: "dsp.rmsHistoryLen",
    label: "RMS history length",
    kind: "discrete",
    options: [256, 512, 1024, 2048, 4096],
    default: 512,
    reconfig: true,
  },
  {
    key: "dsp.hopSize",
    label: "Hop size",
    kind: "discrete",
    options: [256, 512, 1024, 2048],
    default: 1024,
    reconfig: false,
  },
  // Falling-edge length of the analysis window, in samples. Clamped to
  // windowSize/2 in Rust, which is the symmetric Hann — the default, and
  // identical to the old fixed window. Shorter puts the window's peak next to
  // the NEWEST sample instead of the center, cutting ~windowSize/2 samples of
  // onset-detection latency (21 ms at 2048/48k) at the cost of spectral
  // leakage. Sweep it against the `L` latency probe; see docs/latency.md.
  {
    key: "dsp.windowFall",
    label: "window fall (samples)",
    kind: "continuous",
    min: 32,
    max: 2048,
    step: 32,
    default: 2048,
    reconfig: false,
  },
  {
    key: "dsp.smoothingTauSecs",
    label: "fft τ (s)",
    kind: "continuous",
    min: 0.01,
    max: 1.0,
    step: 0.005,
    default: 0.0956,
    reconfig: false,
  },
  {
    key: "dsp.dbFloor",
    label: "fft floor (dB)",
    kind: "continuous",
    min: -120,
    max: -40,
    step: 1,
    default: -100,
    reconfig: false,
  },
  {
    key: "dsp.onsetSmoothingTauSecs",
    label: "Onset release τ (s)",
    kind: "continuous",
    min: 0,
    max: 1,
    step: 0.005,
    default: 0.05,
    reconfig: false,
  },

  {
    key: "dsp.autoGain",
    label: "AutoGain τ (s)",
    kind: "continuous",
    min: 0.05,
    max: 30.0,
    step: 0.05,
    default: 1.0,
    reconfig: false,
  },
  {
    key: "dsp.teaTauSecs",
    label: "beat smooth τ (s)",
    kind: "continuous",
    min: 0.2,
    max: 30.0,
    step: 0.1,
    default: 4.0,
    reconfig: false,
  },
  {
    key: "dsp.acfSmoothingSigma",
    label: "beat blur σ (lag bins)",
    kind: "continuous",
    min: 0.0,
    max: 5.0,
    step: 0.1,
    default: 2.0,
    reconfig: false,
  },
  {
    key: "dsp.acfDecay",
    label: "ACF decay (s)",
    kind: "continuous",
    min: 0.0,
    max: 30.0,
    step: 0.1,
    default: 2.0,
    reconfig: false,
  },

  {
    key: "dsp.phaseLock",
    label: "phase smooth τ (s)",
    kind: "continuous",
    min: 0.05,
    max: 20.0,
    step: 0.05,
    default: 1.0,
    reconfig: false,
  },
];
